import type { MessageCatalog } from '../config'

export const commonMessages = {
  'Language': ['Idioma', 'Langue', 'Idioma', 'Sprache', 'Lingua', 'Taal', '语言', '言語', '언어'],
  'Browser default': ['Idioma del navegador', 'Langue du navigateur', 'Idioma do navegador', 'Browsersprache', 'Lingua del browser', 'Browsertaal', '浏览器默认语言', 'ブラウザーの言語', '브라우저 기본 언어'],
  'Changing language…': ['Cambiando idioma…', 'Changement de langue…', 'Alterando idioma…', 'Sprache wird geändert…', 'Cambio lingua…', 'Taal wijzigen…', '正在切换语言…', '言語を変更中…', '언어 변경 중…'],
  'Page not found': ['Página no encontrada', 'Page introuvable', 'Página não encontrada', 'Seite nicht gefunden', 'Pagina non trovata', 'Pagina niet gevonden', '找不到页面', 'ページが見つかりません', '페이지를 찾을 수 없습니다'],
  'The page you are looking for does not exist or has been moved.': ['La página que buscas no existe o se ha movido.', 'La page recherchée n’existe pas ou a été déplacée.', 'A página que você procura não existe ou foi movida.', 'Die gesuchte Seite existiert nicht oder wurde verschoben.', 'La pagina cercata non esiste o è stata spostata.', 'De gezochte pagina bestaat niet of is verplaatst.', '您要查找的页面不存在或已被移动。', 'お探しのページは存在しないか、移動しました。', '찾으시는 페이지가 없거나 이동되었습니다.'],
  'Go home': ['Ir al inicio', 'Accueil', 'Ir para o início', 'Zur Startseite', 'Vai alla home', 'Naar de startpagina', '返回首页', 'ホームへ', '홈으로'],
  'Browse guides': ['Explorar guías', 'Parcourir les accompagnants', 'Explorar facilitadores', 'Begleitpersonen entdecken', 'Esplora le guide', 'Bekijk begeleiders', '浏览引导师', 'ガイドを探す', '가이드 찾아보기'],
  'Original English article': ['Artículo original en inglés', 'Article original en anglais', 'Artigo original em inglês', 'Englischer Originalartikel', 'Articolo originale in inglese', 'Oorspronkelijk Engelstalig artikel', '英文原文', '英語の原文記事', '영어 원문'],
  'The full safety articles are currently available in English. The summary below is in your selected language.': ['Los artículos completos de seguridad están disponibles actualmente en inglés. El resumen siguiente está en el idioma elegido.', 'Les articles de sécurité complets sont actuellement disponibles en anglais. Le résumé ci-dessous est dans la langue choisie.', 'Os artigos completos de segurança estão disponíveis em inglês. O resumo abaixo está no idioma selecionado.', 'Die vollständigen Sicherheitsartikel sind derzeit auf Englisch verfügbar. Die folgende Zusammenfassung ist in Ihrer gewählten Sprache.', 'Gli articoli completi sulla sicurezza sono attualmente in inglese. Il riepilogo seguente è nella lingua selezionata.', 'De volledige veiligheidsartikelen zijn momenteel in het Engels beschikbaar. De samenvatting hieronder is in je gekozen taal.', '完整的安全指南目前仅提供英文。以下摘要使用您选择的语言。', '安全に関する記事の全文は現在英語で提供されています。以下の要約は選択した言語です。', '안전 관련 전체 기사는 현재 영어로 제공됩니다. 아래 요약은 선택하신 언어로 표시됩니다.'],
  'Read the full article in English': ['Leer el artículo completo en inglés', 'Lire l’article complet en anglais', 'Ler o artigo completo em inglês', 'Vollständigen Artikel auf Englisch lesen', 'Leggi l’articolo completo in inglese', 'Lees het volledige artikel in het Engels', '阅读完整英文文章', '英語の全文を読む', '영어로 전체 기사 읽기'],
  'Sources and service information': ['Fuentes e información de servicios', 'Sources et informations sur les services', 'Fontes e informações sobre serviços', 'Quellen und Informationen zu Diensten', 'Fonti e informazioni sui servizi', 'Bronnen en informatie over diensten', '来源与服务信息', '情報源とサービス情報', '출처 및 서비스 정보'],
  'Last checked': ['Última revisión', 'Dernière vérification', 'Última verificação', 'Zuletzt geprüft', 'Ultima verifica', 'Laatst gecontroleerd', '最后核查', '最終確認', '최종 확인'],
  'A note on this library': ['Una nota sobre esta biblioteca', 'À propos de cette bibliothèque', 'Uma nota sobre esta biblioteca', 'Hinweis zu dieser Bibliothek', 'Una nota su questa biblioteca', 'Een opmerking over deze bibliotheek', '关于本资料库', 'このライブラリーについて', '자료실 안내'],
  'Practical information about preparation, integration, and choosing support. This is not medical advice.': ['Información práctica sobre preparación, integración y elección de apoyo. No es asesoramiento médico.', 'Des informations pratiques sur la préparation, l’intégration et le choix d’un accompagnement. Ce ne sont pas des conseils médicaux.', 'Informações práticas sobre preparação, integração e escolha de apoio. Não são orientações médicas.', 'Praktische Informationen zu Vorbereitung, Integration und der Wahl einer Begleitung. Dies ist keine medizinische Beratung.', 'Informazioni pratiche su preparazione, integrazione e scelta del supporto. Non sono consigli medici.', 'Praktische informatie over voorbereiding, integratie en het kiezen van ondersteuning. Dit is geen medisch advies.', '关于准备、整合和选择支持的实用信息。这不构成医疗建议。', '準備、統合、支援の選び方に関する実用的な情報です。医療上の助言ではありません。', '준비, 통합, 지원 선택에 관한 실용적인 정보입니다. 의료 조언이 아닙니다.'],
  'In the US, call or text 988 for emotional distress or suicidal crisis. For immediate danger or a medical emergency, call 911. Outside the US, contact your local emergency or crisis service.': ['En EE. UU., llama o envía un mensaje al 988 ante angustia emocional o crisis suicida. En caso de peligro inmediato o emergencia médica, llama al 911. Fuera de EE. UU., contacta con los servicios locales de emergencia o crisis.', 'Aux États-Unis, appelez le 988 ou envoyez un SMS en cas de détresse émotionnelle ou de crise suicidaire. En cas de danger immédiat ou d’urgence médicale, appelez le 911. Ailleurs, contactez les services d’urgence ou de crise locaux.', 'Nos EUA, ligue ou envie uma mensagem para 988 em caso de sofrimento emocional ou crise suicida. Em perigo imediato ou emergência médica, ligue 911. Fora dos EUA, contate o serviço local de emergência ou crise.', 'In den USA bei seelischer Not oder einer suizidalen Krise 988 anrufen oder eine SMS senden. Bei unmittelbarer Gefahr oder einem medizinischen Notfall 911 anrufen. Außerhalb der USA örtliche Notfall- oder Krisendienste kontaktieren.', 'Negli Stati Uniti, chiama o invia un SMS al 988 in caso di disagio emotivo o crisi suicidaria. Per pericolo immediato o emergenza medica, chiama il 911. Fuori dagli Stati Uniti, contatta il servizio locale di emergenza o crisi.', 'Bel of sms in de VS 988 bij emotionele nood of een suïcidale crisis. Bel 911 bij direct gevaar of een medisch noodgeval. Neem buiten de VS contact op met de plaatselijke nood- of crisisdienst.', '在美国，如有情绪困扰或自杀危机，请拨打988或发送短信至988。如有紧急危险或医疗急症，请拨打911。在美国以外，请联系当地急救或危机干预服务。', '米国では、精神的な苦痛や自殺の危機にある場合、988に電話またはSMSを送ってください。差し迫った危険や医療上の緊急事態では911に電話してください。米国外では、地域の緊急・危機支援サービスに連絡してください。', '미국에서 정서적 고통이나 자살 위기 시 988로 전화하거나 문자하세요. 즉각적인 위험이나 의료 응급 상황에서는 911로 전화하세요. 미국 외 지역에서는 현지 응급 또는 위기 지원 기관에 연락하세요.'],
  'These guides are for information only. Consult a qualified healthcare professional about your individual situation.': ['Estas guías son solo informativas. Consulta a un profesional sanitario cualificado sobre tu situación personal.', 'Ces guides sont uniquement informatifs. Consultez un professionnel de santé qualifié pour votre situation personnelle.', 'Estes guias são apenas informativos. Consulte um profissional de saúde qualificado sobre sua situação individual.', 'Diese Leitfäden dienen nur der Information. Besprechen Sie Ihre persönliche Situation mit einer qualifizierten medizinischen Fachkraft.', 'Queste guide sono solo informative. Consulta un professionista sanitario qualificato sulla tua situazione personale.', 'Deze gidsen dienen alleen ter informatie. Bespreek je persoonlijke situatie met een bevoegde zorgverlener.', '这些指南仅供参考。请就您的个人情况咨询合格的医疗专业人员。', 'これらのガイドは情報提供のみを目的としています。ご自身の状況については、資格のある医療専門家にご相談ください。', '이 가이드는 정보 제공용입니다. 개인 상황에 대해서는 자격을 갖춘 의료 전문가와 상담하세요.'],
  'Something went wrong': ['Algo salió mal', 'Une erreur est survenue', 'Algo deu errado', 'Etwas ist schiefgelaufen', 'Si è verificato un errore', 'Er ging iets mis', '出现错误', '問題が発生しました', '문제가 발생했습니다'],
  'Try again': ['Volver a intentar', 'Réessayer', 'Tentar novamente', 'Erneut versuchen', 'Riprova', 'Opnieuw proberen', '重试', '再試行', '다시 시도'],
  'An unexpected error occurred. You can try again or return to the home page.': ['Se produjo un error inesperado. Puedes volver a intentarlo o regresar al inicio.', 'Une erreur inattendue est survenue. Vous pouvez réessayer ou revenir à l’accueil.', 'Ocorreu um erro inesperado. Tente novamente ou volte ao início.', 'Ein unerwarteter Fehler ist aufgetreten. Versuchen Sie es erneut oder kehren Sie zur Startseite zurück.', 'Si è verificato un errore imprevisto. Puoi riprovare o tornare alla home.', 'Er is een onverwachte fout opgetreden. Probeer het opnieuw of ga terug naar de startpagina.', '发生了意外错误。您可以重试或返回首页。', '予期しないエラーが発生しました。再試行するか、ホームに戻ってください。', '예기치 않은 오류가 발생했습니다. 다시 시도하거나 홈으로 돌아가세요.'],
} satisfies MessageCatalog
